Organizations:
  - &OrdererOrg
    Name: OrdererOrg
    ID: OrdererMSP
    MSPDir: ../organizations/ordererOrganizations/scholar.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"
    OrdererEndpoints:
      - orderer.scholar.com:7050

  - &university
    Name: universityMSP
    ID: universityMSP
    MSPDir: ../organizations/peerOrganizations/university.scholar.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('universityMSP.admin', 'universityMSP.peer', 'universityMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('universityMSP.admin', 'universityMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('universityMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('universityMSP.peer')"
  
  - &scholarshipDepartment
    Name: scholarshipDepartmentMSP
    ID: scholarshipDepartmentMSP
    MSPDir: ../organizations/peerOrganizations/scholarshipDepartment.scholar.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('scholarshipDepartmentMSP.admin', 'scholarshipDepartmentMSP.peer', 'scholarshipDepartmentMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('scholarshipDepartmentMSP.admin', 'scholarshipDepartmentMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('scholarshipDepartmentMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('scholarshipDepartmentMSP.peer')"

  - &treasury
    Name: treasuryMSP
    ID: treasuryMSP
    MSPDir: ../organizations/peerOrganizations/treasury.scholar.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('treasuryMSP.admin', 'treasuryMSP.peer', 'treasuryMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('treasuryMSP.admin', 'treasuryMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('treasuryMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('treasuryMSP.peer')"

  - &auditor
    Name: auditorMSP
    ID: auditorMSP
    MSPDir: ../organizations/peerOrganizations/auditor.scholar.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('auditorMSP.admin', 'auditorMSP.peer', 'auditorMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('auditorMSP.admin', 'auditorMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('auditorMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('auditorMSP.peer')"

Capabilities:  
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_5: true
    
Application: &ApplicationDefaults
  Organizations: []
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  Addresses:
    - orderer.scholar.com:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations: []
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  ChannelUsingRaft:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      OrdererType: etcdraft
      EtcdRaft:
        Consenters:
          - Host: orderer.scholar.com
            Port: 7050
            ClientTLSCert: ../organizations/ordererOrganizations/scholar.com/orderers/orderer.scholar.com/tls/server.crt
            ServerTLSCert: ../organizations/ordererOrganizations/scholar.com/orderers/orderer.scholar.com/tls/server.crt
      Organizations:
        - *OrdererOrg
      Capabilities: *OrdererCapabilities
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *university
        - *scholarshipDepartment
        - *treasury
        - *auditor
      Capabilities: *ApplicationCapabilities